version: "3.2"
volumes:
  doc-manage-mongo-db:
services:
  api:
    container_name: doc-manage
    image: doc-manage:latest
    env_file:
      - .env
    ports:
      - ${APP_PORT:-3000}:${APP_PORT:-3000}
    links:
      - mongo:mongo
  mongo:
    container_name: doc-manage-mongo
    image: mongo:latest
    volumes:
      - doc-manage-mongo-db:/data/db
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}
